**本习题由李政创建，转载及其他形式合作请与我们联系（微信号`maicro42`)，未经授权严禁搬运及二次创作，侵权必究！**

# numpy基本操作练习

## 导入numpy，并查看其版本

In [1]:
import numpy as np
print(np.__version__)

1.21.4


## 题目1：创建一个三行三列，元素全是1的矩阵。

In [2]:
np.array([[ 0., 0., 0.],
          [ 0., 0., 0.],
          [ 0., 0., 0.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 题目2：创建5阶单位矩阵

In [3]:
result = np.diag([1,1,1,1,1])
result

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## 题目3：生成8行8列的二维数组，值为1-999随机数

In [4]:
data = np.random.randint(1, 999, [8, 8])
data

array([[607, 367, 196, 395, 377, 655, 775, 915],
       [520, 706, 672, 466, 675, 107, 115, 201],
       [186, 861, 245, 842, 490, 357, 627, 381],
       [750, 509, 243,  76,  66, 506, 869, 352],
       [597, 533, 609,  72, 339, 688, 436,  70],
       [489, 411, 194, 695, 330, 310, 156, 647],
       [206, 602, 483, 700, 716,  94, 865, 995],
       [145, 510, 560, 632, 294, 503, 490, 455]])

## 题目4：找到每列的最大值

In [5]:
np.amax(data, axis=0)

array([750, 861, 672, 842, 716, 688, 869, 995])

## 题目5：找到每行的最大值

In [6]:
np.amin(data, axis=1)

array([196, 107, 186,  66,  70, 156,  94, 145])