**本习题由李政创建，转载及其他形式合作请与我们联系（微信号`maicro42`)，未经授权严禁搬运及二次创作，侵权必究！**

# numpy基本操作练习

## 导入numpy，并查看其版本

In [4]:
import numpy as np
print(np.__version__)

1.20.3


## 题目1：创建一个三行三列，元素全是1的矩阵。

In [5]:
np.array([[ 0., 0., 0.],
          [ 0., 0., 0.],
          [ 0., 0., 0.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 题目2：创建5阶单位矩阵

In [6]:
result = np.diag([1,1,1,1,1])
result

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## 题目3：生成8行8列的二维数组，值为1-999随机数

In [7]:
data = np.random.randint(1, 999, [8, 8])
data

array([[697, 939, 307, 155, 540, 708, 788, 948],
       [361,  22, 363, 251, 300, 776, 428, 619],
       [ 49, 944, 791, 490, 358, 887, 777, 596],
       [555, 394, 305, 705, 697, 938, 681, 570],
       [612, 845, 958, 126, 666, 207, 582,  84],
       [605,  21, 635, 842, 721, 556, 766, 439],
       [696, 790, 958, 538, 889, 943, 294, 151],
       [469, 133, 614, 321, 677, 441, 766, 637]])

## 题目4：找到每列的最大值

In [8]:
np.amax(data, axis=0)

array([697, 944, 958, 842, 889, 943, 788, 948])

## 题目5：找到每行的最大值

In [9]:
np.amin(data, axis=1)

array([155,  22,  49, 305,  84,  21, 151, 133])